name: ScreenRotationAPI
version: 1.1-SNAPSHOT
main: nl.parkcircle.ScreenRotationAPI
authors: [Mindgamsenl, Casdraakje]
description: ScreenRotationAPI
depend: [ProtocolLib]
commands:
   screenrotationapi:
      description: kloten command

permissions:
  screenAPI.set:
    description: the cool command
    default: op